In [3]:
import numpy as np

In [4]:
np.__version__

'1.24.3'

In [5]:
array1=np.array([1,2,3])
array1

array([1, 2, 3])

In [6]:
type(array1)

numpy.ndarray

In [11]:
arr2d=np.array([[1,2],[3,4]])
arr2d

array([[1, 2],
       [3, 4]])

In [13]:
arr2d=np.array([[1,2,3.3],[3,4,6.5]])
arr2d

array([[1. , 2. , 3.3],
       [3. , 4. , 6.5]])

In [20]:
arr=np.array([[[1,2],[3,4]],
              [[5,6],[7,8]]])
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [22]:
arr2=np.array([[[2,3,3],[4,5,6],[6,7,8]],[[3,6,7],[5,6,7],[7,8,9]]])
arr2

array([[[2, 3, 3],
        [4, 5, 6],
        [6, 7, 8]],

       [[3, 6, 7],
        [5, 6, 7],
        [7, 8, 9]]])

In [24]:
arr3=np.array((12,13,14))
arr3

array([12, 13, 14])

In [25]:
array1.ndim

1

In [26]:
arr2.ndim

3

In [32]:
arr4= np.array([1,2,3,5],ndmin=4)
arr4

array([[[[1, 2, 3, 5]]]])

In [33]:
arr4.shape

(1, 1, 1, 4)

In [34]:
arr3.shape

(3,)

In [35]:
arr2.shape

(2, 3, 3)

In [39]:
arr2[0][1][2]

6

In [45]:
for x in range(0,2):
    for y in range(0,3):
        print(arr2[x][y])

[2 3 3]
[4 5 6]
[6 7 8]
[3 6 7]
[5 6 7]
[7 8 9]


In [46]:
arr2d.dtype

dtype('float64')

In [49]:
arr2.dtype

dtype('int32')

In [52]:
arr5=np.array([1,2,3,4,5],dtype='S')
arr5

array([b'1', b'2', b'3', b'4', b'5'], dtype='|S1')

In [56]:
arr2dconv=arr2d.astype('i')
arr2dconv

array([[1, 2, 3],
       [3, 4, 6]], dtype=int32)

In [58]:
arr2conv=arr2.astype('f')
arr2conv

array([[[2., 3., 3.],
        [4., 5., 6.],
        [6., 7., 8.]],

       [[3., 6., 7.],
        [5., 6., 7.],
        [7., 8., 9.]]], dtype=float32)

In [67]:
numone=np.ones((2,2),dtype=int)
numone

array([[1, 1],
       [1, 1]])

In [73]:
num1=np.ones((2,3,3))
num1

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [75]:
num2=np.zeros((3,2),dtype=int)
num2

array([[0, 0],
       [0, 0],
       [0, 0]])

In [81]:
num3=np.arange(1,90,2,dtype='i')
num3

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89], dtype=int32)

In [87]:
num4=np.random.randint(low=1,size=5)
num4

array([0, 0, 0, 0, 0])

In [88]:
b=np.random.randint(low=1,high=6,size=(2,3))
b

array([[2, 1, 4],
       [4, 2, 4]])

In [92]:
array2=[3,4,5]

In [94]:
np.concatenate([array1,array2])

array([1, 2, 3, 3, 4, 5])

In [97]:
flatarr=arr2.flatten()
flatarr

array([2, 3, 3, 4, 5, 6, 6, 7, 8, 3, 6, 7, 5, 6, 7, 7, 8, 9])

In [99]:
np.reshape(flatarr[:4],(2,2))

array([[2, 3],
       [3, 4]])

In [103]:
np.eye(5,dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [106]:
import pandas as pd
df=pd.DataFrame(array1)
df

0
0  1
1  2
2  3